### ISSUE TITLE
Titles and subtitles

### ISSUE THREAD

**Issue by cforgaci** [UD3-Lab/mintEMU#58]
I checked again and updated the metadata file. I noticed that the title and subtitle are in the same field. This might be an issue when we remove strings from the metadata in the cleaning stage, as some authors only use the title, without the subtitle, in the body of the thesis, and that way we fail to remove it. Should I separate them into two columns in the metadata so that we can remove them as separate fields when using `find_meta_stopwords()`?

**Comment by cforgaci** [comment]
Note that:  
- not all theses have subtitles
- some theses have two subtitles 😞
- the subtitle is not always the same on the cover and inside the thesis
- some titles/subtitles use numbers and symbols that we might want to keep
- some titles/subtitles are inconsistent in the use of British and US English

**Comment by alwil** [comment]
To clean the data steps should bd: 
- add a symbol ( e.g. colon)  to the metadata file, columns 'Title' so that title-subtitle split is consistent and easily recognised
- create two additional columns : title; subtitle; rename the initial column to 'full_title' - use `merge-metadatata-files.R` 
- update defaults in the metadata function

**Comment by cforgaci** [comment]
Done, see #64
